console.log(" har\"".length);
let Emp_name = "kamal joshi";
let Emp = Emp_name.toUpperCase();
console.log(Emp_name.includes("joshi"));
console.log(Emp_name.endsWith("hi"));
console.log(Emp_name.startsWith('ka'));
console.log(Emp.toLowerCase());
console.log(Emp);
console.log(Emp_name.replace('l','k'));
console.log(Emp_name.replace(Emp_name[4],'k'));
