let person_name = " kamal chandra joshi ";
// console.log(person_name.toUpperCase());
// console.log(person_name.toLowerCase());
// console.log(person_name.length);
// console.log(person_name.charAt(6));
// console.log(person_name.slice(5,13));
// console.log(person_name.slice(14));
// console.log(person_name.slice(0,6));
// console.log(person_name.trimStart());
// console.log(person_name.trimEnd());
// console.log(person_name.trim());
// console.log(person_name.charCodeAt(0));
// console.log(person_name.charAt(1));
// console.log(person_name.startsWith(" "));
// console.log(person_name.endsWith(" "));
// console.log(person_name.startsWith("k"));
// console.log(person_name.endsWith("i"));
// console.log(person_name.includes("kamal"));
// console.log(person_name.includes("joshi"));
// console.log(person_name.includes("chandra"));
// console.log(person_name.includes("pant"));
// console.log(person_name.trim().concat(" has a great personality."));
// console.log(person_name.concat(" is a bad boy."));
// console.log(person_name.trim().substring(0,4));
// console.log(person_name.trim().slice(0,4));
let new_name = person_name.toUpperCase();
console.log(new_name);
let course = "BCA";
let age = 22;
let university = "Surajmal University";
console.log(`The name of the student is ${person_name.trim()} he is ${age} years old and he is doing ${course} from ${university}`);

